name: test
on:
  - push
jobs:
  chezmoi-apply-test:
    strategy:
     matrix:
       os: [ubuntu-latest, macos-latest]
    name: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v4
      - name: Install dotfiles
        run: >-
          sh -c "$(curl -fsLS chezmoi.io/getlb)" -- init --apply --verbose --no-tty tk09291197
          --promptString email=test@example.com,name=user1
