name: test
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
jobs:
  chezmoi-apply-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 300
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dotfiles
        run: >-
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin" \
              init --apply --verbose --no-tty tk09291197 --promptString email=test@example.com,name=user1
